# Generated by Django 5.0.1 on 2025-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientip', models.IntegerField()),
                ('clientname', models.CharField(max_length=50)),
                ('clientcount', models.IntegerField()),
                ('clienttime', models.DateTimeField()),
            ],
        ),
    ]
