# Generated by Django 5.0.1 on 2025-02-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_userinfo_clientip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='clientcount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='clienttime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
