# Generated by Django 5.0.1 on 2025-02-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_userinfo_clientcount_alter_userinfo_clienttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='clientcount',
            field=models.IntegerField(default=0),
        ),
    ]
