# Generated by Django 5.0.1 on 2025-02-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userinfo_user_alter_userinfo_clientcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='clienturl',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
