# Generated by Django 5.0.1 on 2025-02-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_userinfo_clientdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='clientdata',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='clientview',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
